// Builders for the downloadable artifacts (CSV, Markdown report, Jupyter notebook, Python template).

import Papa from 'papaparse';
import { NOTABLE_CORRELATION, formatNumber, formatPct } from './analysis';
import { guessTarget } from './blueprints';

export function downloadFile(filename, content, type) {
    const url = URL.createObjectURL(new Blob([content], { type }));
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
}

export const baseName = (name) => name.replace(/\.(csv|json|tsv|txt)$/i, '');

const stripMarkup = (text) => text.replace(/\*\*/g, '');

/** Python string literal for an arbitrary column name. */
const py = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const pyList = (items) => `[${items.map(py).join(', ')}]`;

export const buildCsv = (dataset) => Papa.unparse(dataset.data, { columns: dataset.columns });

export function buildReport(dataset, analysis) {
    const { stats, insights, correlations, categoricalDists } = analysis;

    const columnSections = dataset.columns.map((col) => {
        const s = stats[col];
        if (s.type === 'numeric') {
            return [
                `### ${col} (numeric)`,
                `- **Mean:** ${formatNumber(s.mean)}`,
                `- **Median:** ${formatNumber(s.median)}`,
                `- **Std dev:** ${formatNumber(s.std)}`,
                `- **CV:** ${s.cv == null ? 'N/A' : formatPct(s.cv)}`,
                `- **Range:** ${formatNumber(s.min)} – ${formatNumber(s.max)}`,
                `- **Missing:** ${formatPct(s.missingPct)}`,
            ].join('\n');
        }
        const top = (categoricalDists[col] || [])
            .slice(0, 3)
            .map((d) => `${d.name} (${d.percentage.toFixed(1)}%)`)
            .join(', ');
        return [
            `### ${col} (categorical)`,
            `- **Unique values:** ${s.unique}`,
            `- **Mode:** ${s.mode}`,
            `- **Missing:** ${formatPct(s.missingPct)}`,
            `- **Top categories:** ${top}`,
        ].join('\n');
    });

    const notable = correlations.filter((c) => Math.abs(c.correlation) > NOTABLE_CORRELATION);

    return `# DataMind Analysis Report

**Dataset:** ${dataset.name}
**Date:** ${new Date().toLocaleDateString()}
**Records:** ${dataset.data.length}
**Features:** ${dataset.columns.length}

## Key insights

${insights.map((i) => `- **[${i.agent}]** ${stripMarkup(i.text)}`).join('\n')}

## Statistical summary

${columnSections.join('\n\n')}

## Correlations (|r| > ${NOTABLE_CORRELATION})

${notable.length ? notable.map((c) => `- **${c.col1}** vs **${c.col2}**: ${c.correlation.toFixed(3)}`).join('\n') : '_None found._'}

---
*Generated by DataMind*
`;
}

export function buildNotebook(dataset) {
    const script = `import pandas as pd
import numpy as np

# Load the data (assumes the file sits next to this notebook)
df = pd.read_csv(${py(dataset.name)})
print(f"Loaded dataset with shape: {df.shape}")

# 1. Overview
df.info()
print("\\nMissing values:")
print(df.isnull().sum())

# 2. Numeric summary
print("\\nNumeric summary:")
print(df.describe())

# 3. Top correlations
numeric_cols = df.select_dtypes(include=[np.number]).columns
if len(numeric_cols) > 1:
    corr = df[numeric_cols].corr().unstack()
    corr = corr[corr.index.get_level_values(0) < corr.index.get_level_values(1)]
    print("\\nTop correlations:")
    print(corr.abs().sort_values(ascending=False).head(5))

# 4. Categorical frequencies
for col in df.select_dtypes(include='object').columns:
    print(f"\\n{col} frequencies (%):")
    print(df[col].value_counts(normalize=True).mul(100).round(2))
`;

    const notebook = {
        cells: [
            {
                cell_type: 'markdown',
                metadata: {},
                source: [
                    `# DataMind analysis: ${dataset.name}\n\n`,
                    `**Generated:** ${new Date().toLocaleDateString()}  \n`,
                    `**Records:** ${dataset.data.length}  \n`,
                    `**Features:** ${dataset.columns.length}`,
                ],
            },
            { cell_type: 'code', execution_count: null, metadata: {}, outputs: [], source: [script] },
        ],
        metadata: {
            kernelspec: { display_name: 'Python 3', language: 'python', name: 'python3' },
            language_info: { name: 'python', file_extension: '.py', mimetype: 'text/x-python' },
        },
        nbformat: 4,
        nbformat_minor: 5,
    };
    return JSON.stringify(notebook, null, 1);
}

export function buildPythonTemplate(analysis) {
    const { numericCols, categoricalCols } = analysis;
    const target = guessTarget(numericCols);

    return `# Advanced EDA visualizations, generated by DataMind
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)

# df = pd.read_csv("your_file.csv")

numerical_cols = ${pyList(numericCols)}
categorical_cols = ${pyList(categoricalCols)}

# 1. Distributions
if numerical_cols:
    df[numerical_cols].hist(bins=30, figsize=(15, 12), edgecolor="black")
    plt.suptitle("Distribution of numerical variables", fontsize=16)
    plt.tight_layout()
    plt.show()

    df.boxplot(column=numerical_cols, figsize=(15, 6), vert=False)
    plt.title("Outlier detection")
    plt.show()

# 2. Correlation heatmap
if len(numerical_cols) > 1:
    sns.heatmap(df[numerical_cols].corr(), annot=True, cmap="BrBG", center=0, fmt=".2f")
    plt.title("Correlation matrix")
    plt.show()

# 3. Group statistics
target = ${target ? py(target) : 'None'}
if target and categorical_cols:
    print(df.groupby(categorical_cols[0])[target].agg(["count", "mean", "median", "std", "min", "max"]).round(2))

# 4. Categorical frequencies
for col in categorical_cols:
    order = df[col].value_counts().index[:15]
    sns.countplot(y=df[col], order=order, color="#5f7f45")
    plt.title(f"Frequency of {col}")
    plt.show()
`;
}
