// Plain-language explanations shown in the ⓘ info tips throughout the app.

export const GLOSSARY = {
    records: 'Rows in the dataset. Each row is one observation, such as an order or a customer.',
    features: 'Columns in the dataset. Each column describes one attribute of every record.',
    numeric: 'Columns where at least 90% of filled values are numbers. These get statistics and histograms.',
    categorical: 'Columns holding labels or text, such as Region or Color. These get frequency breakdowns.',
    completeness: 'Share of all cells (rows × columns) that contain a value. 100% means nothing is missing.',
    strongCorrelations: 'Pairs of numeric columns with |r| above 0.7: when one moves, the other tends to move with it.',
    mean: 'The arithmetic average: the sum of values divided by their count. Sensitive to outliers.',
    median: 'The middle value once sorted. Half the values are below it, half above. Robust to outliers.',
    std: 'Standard deviation: the typical distance of a value from the mean. Larger means more spread out.',
    cv: 'Coefficient of variation = std ÷ mean × 100. Compares spread across columns with different units. Above 50% is highly variable.',
    min: 'The smallest value observed.',
    max: 'The largest value observed.',
    missing: 'Percentage of records where this column is empty.',
    histogram: 'Values are split into 15 equal-width bins; each bar shows how many records fall in that range.',
    donut: 'Share of records in each category. Categories beyond the top 7 are grouped into “Other”.',
    correlation: 'Pearson’s r runs from −1 to +1. +1 means the two columns rise together perfectly, −1 means one falls as the other rises, 0 means no linear relationship.',
    bivariate: 'For each category, the bar shows the mean of a numeric column and the dot shows its median. A large gap between them signals skew inside that group.',
    insights: 'Automatic findings from scanning every column: skew, outliers, dominant categories, missing data and strong correlations.',
    decision: 'Condenses the analysis into the few items that most deserve a decision-maker’s attention.',
    quality: 'A health check of the dataset: completeness, consistency and columns that look like IDs.',
    cardinality: 'A categorical column where more than 80% of values are unique is probably an identifier, not a grouping.',
    segmentation: 'Two starting customer profiles: the group with the highest average value, and the group with the most volume.',
    predictive: 'Ranks numeric columns by how useful they may be for predicting the target column.',
    riskScore: 'Score = |r with target| ÷ CV. Rewards columns that track the target closely while staying stable.',
    skew: 'When a group’s mean sits well above its median, a few very high values are pulling the average up.',
    template: 'Python code you can paste into Jupyter or Colab to reproduce these charts with pandas and seaborn.',
    sampling: 'To keep the browser responsive, statistics are computed on 110,000 rows sampled evenly from the start to the end of the file. Record counts and exports always include every row.',
    privacy: 'Files are parsed with JavaScript on your device and saved in this browser’s own storage (IndexedDB). Nothing is uploaded to a server.',
};
