// Plain-language explanations shown in the ⓘ info tips throughout the app.

export const GLOSSARY = {
    records: 'Rows in the dataset. Every row in the file is read and counted — nothing is sampled.',
    features: 'Columns in the dataset. Each column describes one attribute of every record.',
    numeric: 'Columns where at least 90% of filled values are numbers. These get statistics, histograms, box plots and more.',
    categorical: 'Columns holding labels or text, such as Region or Color. These get frequency breakdowns.',
    dates: 'Columns of ISO dates (YYYY-MM-DD, optionally with a time). These get a timeline of records over time.',
    completeness: 'Share of all cells (rows × columns) holding a usable value. 100% means nothing is missing.',
    strongCorrelations: 'Pairs of numeric columns with |r| above 0.7: when one moves, the other tends to move with it.',
    mean: 'The arithmetic average: the sum of values divided by their count. Sensitive to outliers. Always exact.',
    median: 'The middle value once sorted. Half the values are below it, half above. Robust to outliers.',
    std: 'Sample standard deviation (n − 1 in the denominator, like pandas): the typical distance of a value from the mean. Always exact.',
    cv: 'Coefficient of variation = std ÷ |mean| × 100. Compares spread across columns with different units. Above 50% is highly variable.',
    skewness: 'Asymmetry of the distribution (bias-corrected, like pandas). 0 is symmetric; above +1 has a long right tail; below −1 a long left tail.',
    kurtosis: 'Excess kurtosis (like pandas): 0 for a normal distribution. Positive values mean heavier tails and more extreme values.',
    min: 'The smallest value observed.',
    max: 'The largest value observed.',
    missing: 'Percentage of records where this column is empty or holds a missing-value marker such as NA, null or N/A.',
    invalid: 'Values in a numeric column that are not numbers (for example “1,200” or “n/a ”). They are excluded from the statistics.',
    histogram: 'Values split into equal-width bins with round edges. Each bin includes its left edge; the last bin also includes its right edge. Bar height = number of records.',
    valueBars: 'When a column has 30 or fewer distinct values, each value gets its own bar — an exact count with no binning.',
    boxplot: 'The box spans the 25th to 75th percentile, with the median as a line. Whiskers reach the most extreme values within 1.5 × IQR; values beyond are outliers.',
    ecdf: 'Cumulative distribution: for any value on the x-axis, the share of records at or below it. Read it as “P90 = 90% of records are at most this value”.',
    qq: 'Q-Q plot against a normal distribution with the same mean and std. Points on the diagonal mean the data is normal; curves away from it reveal skew and heavy tails.',
    percentiles: 'Pxx is the value below which xx% of records fall, using linear interpolation like pandas.',
    outliers: 'Values below Q1 − 1.5 × IQR or above Q3 + 1.5 × IQR (the box-plot rule).',
    exactness:
        'Counts, means, std, skewness, min/max, correlations and group means are always computed exactly over every row. Medians, percentiles and histograms are also exact for files up to about 2 million rows, for columns with ≤ 1,024 distinct values, and for whole-number columns spanning up to 262,144 values (prices, ages, counts, years). Otherwise they come from a streaming sketch accurate to ±0.1% of the value (marked ≈).',
    donut: 'Share of records in each category. Categories beyond the top 7 are grouped into “Other”.',
    categoryBars: 'Number of records per category, longest first. Bars make small differences easier to compare than a donut.',
    timeline: 'Records per day, week, month or year — or the average of a numeric column over time.',
    correlation: 'Pearson’s r from −1 to +1, computed over every row where both columns have values. +1 means they rise together perfectly, −1 means one falls as the other rises, 0 means no linear relationship.',
    bivariate: 'For each category: the bar shows the exact mean of the numeric column and the dot its median. A big gap signals skew inside that group.',
    groupBox: 'One box plot per category, so you can compare medians, spread and outliers between groups.',
    scatter: 'Dots are a uniform random sample of up to 5,000 rows (to keep the chart readable). The trend line and r are computed from every row.',
    insights: 'Automatic findings from scanning every column: skew, outliers, invalid values, dominant categories, missing data and strong correlations.',
    decision: 'Condenses the analysis into the few items that most deserve a decision-maker’s attention.',
    quality: 'A health check of the dataset: completeness, invalid values, consistency and columns that look like IDs.',
    cardinality: 'Columns that look like identifiers: numeric counters, or text columns where more than 80% of values are unique.',
    segmentation: 'Two starting customer profiles: the group with the highest average value, and the group with the most volume.',
    predictive: 'Ranks numeric columns by how useful they may be for predicting the target column.',
    riskScore: 'Score = |r with target| ÷ CV. Rewards columns that track the target closely while staying stable.',
    skew: 'When a group’s mean sits well above its median, a few very high values are pulling the average up.',
    template: 'Python code you can paste into Jupyter or Colab to reproduce these charts with pandas and seaborn.',
    preview: 'The first 20 rows of the file, exactly as written.',
    exportImage: 'Downloads just the plot — title, axes and legend on white, without tooltips or hover highlights. PNG is 2× resolution; SVG stays sharp at any size.',
    privacy: 'Files are read with JavaScript on your device, using every CPU core, and saved in this browser’s own storage (IndexedDB). Nothing is uploaded to a server.',
    speed: 'The file is split across your CPU cores and streamed in 4 MB pieces, so memory stays flat no matter how big the file is.',
};
